# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/SoC/activecore/designs/rtl/sigma/syn/syn_6stage/NEXYS4_DDR/NEXYS4_DDR.srcs/sources_1/ip/sys_clk/sys_clk.xci
# IP: The module: 'sys_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SoC/activecore/designs/rtl/sigma/syn/syn_6stage/NEXYS4_DDR/NEXYS4_DDR.srcs/sources_1/ip/sys_clk/sys_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/SoC/activecore/designs/rtl/sigma/syn/syn_6stage/NEXYS4_DDR/NEXYS4_DDR.srcs/sources_1/ip/sys_clk/sys_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/SoC/activecore/designs/rtl/sigma/syn/syn_6stage/NEXYS4_DDR/NEXYS4_DDR.srcs/sources_1/ip/sys_clk/sys_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/SoC/activecore/designs/rtl/sigma/syn/syn_6stage/NEXYS4_DDR/NEXYS4_DDR.srcs/sources_1/ip/sys_clk/sys_clk.xci
# IP: The module: 'sys_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SoC/activecore/designs/rtl/sigma/syn/syn_6stage/NEXYS4_DDR/NEXYS4_DDR.srcs/sources_1/ip/sys_clk/sys_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/SoC/activecore/designs/rtl/sigma/syn/syn_6stage/NEXYS4_DDR/NEXYS4_DDR.srcs/sources_1/ip/sys_clk/sys_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/SoC/activecore/designs/rtl/sigma/syn/syn_6stage/NEXYS4_DDR/NEXYS4_DDR.srcs/sources_1/ip/sys_clk/sys_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
