// ===========================================================
// HLS sources generated by ActiveCore framework
// Date: 2022-11-19 23:51:00
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

#include <ap_int.h>
#include <hls_stream.h>
#include "riscv_1stage.hpp"

typedef struct {
	ap_uint<1> if_id;
	ap_uint<1> resp_done;
	ap_uint<32> rdata;
	ap_uint<1> rdreq_pending;
	ap_uint<1> tid;
} genmcopipe_handle_instr_mem_struct;

typedef struct {
	ap_uint<1> if_id;
	ap_uint<1> resp_done;
	ap_uint<32> rdata;
	ap_uint<1> rdreq_pending;
	ap_uint<2> tid;
} genmcopipe_handle_coproc_M_if_struct;

typedef struct {
	ap_uint<1> if_id;
	ap_uint<1> resp_done;
	ap_uint<32> rdata;
	ap_uint<1> rdreq_pending;
	ap_uint<1> tid;
} genmcopipe_handle_data_mem_struct;

typedef struct {
	ap_uint<1> instr_req_done;
	ap_uint<1> irq_recv;
	ap_uint<8> irq_mcause;
	ap_uint<1> Ext_coproc_req_done;
	ap_uint<1> jump_req_done;
	ap_uint<1> data_req_done;
	genmcopipe_handle_instr_mem_struct genmcopipe_handle_instr_mem;
	genmcopipe_handle_coproc_M_if_struct genmcopipe_handle_coproc_M_if;
	genmcopipe_handle_data_mem_struct genmcopipe_handle_data_mem;
} genpstage_EXEC_TRX_BUF_STRUCT;

typedef struct {
	ap_uint<1> instr_req_done;
	ap_uint<32> curinstr_addr;
	ap_uint<32> nextinstr_addr;
	riscv_1stage_busreq_mem_struct instr_busreq;
	ap_uint<32> instr_code;
	ap_uint<7> opcode;
	ap_uint<1> alu_unsigned;
	ap_uint<5> rs1_addr;
	ap_uint<5> rs2_addr;
	ap_uint<5> rd_addr;
	ap_uint<3> funct3;
	ap_uint<7> funct7;
	ap_uint<5> shamt;
	ap_uint<4> pred;
	ap_uint<4> succ;
	ap_uint<12> csrnum;
	ap_uint<5> zimm;
	ap_uint<32> immediate_I;
	ap_uint<32> immediate_S;
	ap_uint<32> immediate_B;
	ap_uint<32> immediate_U;
	ap_uint<32> immediate_J;
	ap_uint<2> op1_source;
	ap_uint<1> rd_req;
	ap_uint<3> rd_source;
	ap_uint<32> immediate;
	ap_uint<2> op2_source;
	ap_uint<1> alu_req;
	ap_uint<4> alu_opcode;
	ap_uint<1> jump_req;
	ap_uint<1> jump_src;
	ap_uint<1> rs1_req;
	ap_uint<1> rs2_req;
	ap_uint<1> jump_req_cond;
	ap_uint<1> mem_req;
	ap_uint<1> mem_cmd;
	ap_uint<1> ext_coproc_req;
	ap_uint<1> m_ext_req;
	ap_uint<1> fencereq;
	ap_uint<1> ebreakreq;
	ap_uint<1> ecallreq;
	ap_uint<1> csrreq;
	ap_uint<1> custom0_ext_req;
	ap_uint<4> mem_be;
	ap_uint<1> load_signext;
	ap_uint<1> mret_req;
	ap_uint<32> rs1_rdata;
	ap_uint<32> rs2_rdata;
	ap_uint<32> csr_rdata;
	ap_uint<32> alu_op1;
	ap_uint<32> alu_op2;
	ap_uint<33> alu_op1_wide;
	ap_uint<33> alu_op2_wide;
	ap_uint<8> irq_mcause;
	ap_uint<1> irq_recv;
	riscv_1stage_Ext_coproc_struct Ext_coproc_busreq;
	ap_uint<1> Ext_coproc_req_done;
	ap_uint<33> alu_result_wide;
	ap_uint<32> alu_result;
	ap_uint<1> alu_CF;
	ap_uint<1> alu_SF;
	ap_uint<1> alu_ZF;
	ap_uint<1> alu_OF;
	ap_uint<1> alu_overflow;
	ap_uint<32> rd_wdata;
	ap_uint<1> rd_rdy;
	ap_uint<32> curinstraddr_imm;
	ap_uint<32> jump_vector;
	ap_uint<32> mem_addr;
	ap_uint<32> mem_wdata;
	ap_uint<1> jump_req_done;
	riscv_1stage_busreq_mem_struct data_busreq;
	ap_uint<1> data_req_done;
	ap_uint<32> mem_rdata;
} genpstage_EXEC_TRX_LOCAL_STRUCT;

ap_uint<32> genpsticky_glbl_pc;
ap_uint<32> genpsticky_glbl_regfile [32];
ap_uint<1> genpsticky_glbl_jump_req_cmd;
ap_uint<32> genpsticky_glbl_jump_vector_cmd;
ap_uint<8> genpsticky_glbl_CSR_MCAUSE;
ap_uint<1> genpsticky_glbl_MIRQEN;
ap_uint<32> genpsticky_glbl_MRETADDR;
ap_uint<1> genmcopipe_instr_mem_wr_done;
ap_uint<1> genmcopipe_instr_mem_rd_done;
ap_uint<1> genmcopipe_instr_mem_full_flag;
ap_uint<1> genmcopipe_instr_mem_empty_flag;
ap_uint<1> genmcopipe_instr_mem_wr_ptr;
ap_uint<1> genmcopipe_instr_mem_rd_ptr;
ap_uint<1> genmcopipe_data_mem_wr_done;
ap_uint<1> genmcopipe_data_mem_rd_done;
ap_uint<1> genmcopipe_data_mem_full_flag;
ap_uint<1> genmcopipe_data_mem_empty_flag;
ap_uint<1> genmcopipe_data_mem_wr_ptr;
ap_uint<1> genmcopipe_data_mem_rd_ptr;
ap_uint<1> genmcopipe_coproc_M_if_wr_done;
ap_uint<1> genmcopipe_coproc_M_if_rd_done;
ap_uint<1> genmcopipe_coproc_M_if_full_flag;
ap_uint<1> genmcopipe_coproc_M_if_empty_flag;
ap_uint<2> genmcopipe_coproc_M_if_wr_ptr;
ap_uint<2> genmcopipe_coproc_M_if_rd_ptr;
ap_uint<1> genmcopipe_coproc_custom0_if_wr_done;
ap_uint<1> genmcopipe_coproc_custom0_if_rd_done;
ap_uint<1> genmcopipe_coproc_custom0_if_full_flag;
ap_uint<1> genmcopipe_coproc_custom0_if_empty_flag;
ap_uint<2> genmcopipe_coproc_custom0_if_wr_ptr;
ap_uint<2> genmcopipe_coproc_custom0_if_rd_ptr;
genpstage_EXEC_TRX_BUF_STRUCT genpstage_EXEC_TRX_BUF [0:0];
ap_uint<1> genpstage_EXEC_TRX_BUF_COUNTER;
ap_uint<1> genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY;
ap_uint<1> genpstage_EXEC_TRX_BUF_COUNTER_FULL;
ap_uint<1> genpstage_EXEC_genctrl_stalled_glbl;

void riscv_1stage(ap_uint<1> geninit, hls::stream<ap_uint<8> >& irq_fifo, hls::stream<ap_uint<32> >& genmcopipe_instr_mem_resp, hls::stream<ap_uint<32> >& genmcopipe_data_mem_resp, hls::stream<ap_uint<32> >& genmcopipe_coproc_M_if_resp, hls::stream<ap_uint<32> >& genmcopipe_coproc_custom0_if_resp, hls::stream<genpmodule_riscv_1stage_genmcopipe_instr_mem_genstruct_fifo_wdata>& genmcopipe_instr_mem_req, hls::stream<genpmodule_riscv_1stage_genmcopipe_data_mem_genstruct_fifo_wdata>& genmcopipe_data_mem_req, hls::stream<genpmodule_riscv_1stage_genmcopipe_coproc_M_if_genstruct_fifo_wdata>& genmcopipe_coproc_M_if_req, hls::stream<genpmodule_riscv_1stage_genmcopipe_coproc_custom0_if_genstruct_fifo_wdata>& genmcopipe_coproc_custom0_if_req) {


	ap_uint<1> genmcopipe_instr_mem_wr_ptr_next;
	ap_uint<1> genmcopipe_instr_mem_rd_ptr_next;
	ap_uint<1> genmcopipe_data_mem_wr_ptr_next;
	ap_uint<1> genmcopipe_data_mem_rd_ptr_next;
	ap_uint<2> genmcopipe_coproc_M_if_wr_ptr_next;
	ap_uint<2> genmcopipe_coproc_M_if_rd_ptr_next;
	ap_uint<2> genmcopipe_coproc_custom0_if_wr_ptr_next;
	ap_uint<2> genmcopipe_coproc_custom0_if_rd_ptr_next;
	ap_uint<1> genpstage_EXEC_genpctrl_flushreq;
	genpstage_EXEC_TRX_LOCAL_STRUCT genpstage_EXEC_TRX_LOCAL;
	genpstage_EXEC_TRX_BUF_STRUCT genpstage_EXEC_TRX_PUSHED;
	ap_uint<1> genpstage_EXEC_genctrl_active;
	ap_uint<1> genpstage_EXEC_genctrl_working;
	ap_uint<1> genpstage_EXEC_genctrl_succ;
	ap_uint<1> genpstage_EXEC_genctrl_occupied;
	ap_uint<1> genpstage_EXEC_genctrl_rdy;
	ap_uint<1> genpstage_EXEC_genctrl_new;
	ap_uint<1> genpstage_EXEC_genctrl_finish;
	ap_uint<1> gen154_pipex_succreq;
	ap_uint<32> gen155_pipex_succbuf;
	ap_uint<1> gen156_pipex_var;
	ap_uint<33> gen157_pipex_var;
	ap_uint<1> gen158_pipex_var;
	ap_uint<1> gen159_pipex_var;
	ap_uint<1> gen160_pipex_var;
	ap_uint<1> gen161_pipex_var;
	ap_uint<1> gen162_pipex_var;
	ap_uint<1> gen163_pipex_var;
	ap_uint<1> gen164_pipex_var;
	ap_uint<1> gen165_pipex_var;
	ap_uint<32> gen166_pipex_var;
	ap_uint<1> gen167_pipex_var;
	ap_uint<32> gen168_pipex_var;
	ap_uint<12> gen169_pipex_var;
	ap_uint<1> gen170_pipex_var;
	ap_uint<32> gen171_pipex_var;
	ap_uint<13> gen172_pipex_var;
	ap_uint<1> gen173_pipex_var;
	ap_uint<32> gen174_pipex_var;
	ap_uint<32> gen175_pipex_var;
	ap_uint<21> gen176_pipex_var;
	ap_uint<1> gen177_pipex_var;
	ap_uint<32> gen178_pipex_var;
	ap_uint<1> gen179_pipex_var;
	ap_uint<1> gen180_pipex_var;
	ap_uint<1> gen181_pipex_var;
	ap_uint<1> gen182_pipex_var;
	ap_uint<32> gen183_pipex_var;
	ap_uint<1> gen184_pipex_var;
	ap_uint<1> gen185_pipex_var;
	ap_uint<32> gen186_pipex_var;
	ap_uint<1> gen187_pipex_var;
	ap_uint<1> gen188_pipex_var;
	ap_uint<1> gen189_pipex_var;
	ap_uint<1> gen190_pipex_var;
	ap_uint<1> gen191_pipex_var;
	ap_uint<1> gen192_pipex_var;
	ap_uint<1> gen193_pipex_var;
	ap_uint<1> gen194_pipex_var;
	ap_uint<32> gen195_pipex_var;
	ap_uint<32> gen196_pipex_var;
	ap_uint<32> gen197_pipex_var;
	ap_uint<1> gen198_pipex_var;
	ap_uint<1> gen199_pipex_var;
	ap_uint<1> gen200_pipex_var;
	ap_uint<1> gen201_pipex_var;
	ap_uint<1> gen202_pipex_var;
	ap_uint<32> gen203_pipex_var [32];
	ap_uint<32> gen204_pipex_var [32];
	ap_uint<1> gen205_pipex_var;
	ap_uint<1> gen206_pipex_var;
	ap_uint<1> gen207_pipex_var;
	ap_uint<1> gen208_pipex_var;
	ap_uint<1> gen209_pipex_var;
	ap_uint<1> gen210_pipex_var;
	ap_uint<33> gen211_pipex_var;
	ap_uint<33> gen212_pipex_var;
	ap_uint<1> gen213_pipex_var;
	ap_uint<1> gen214_pipex_var;
	ap_uint<33> gen215_pipex_var;
	ap_uint<1> gen216_pipex_var;
	ap_uint<33> gen217_pipex_var;
	ap_uint<1> gen218_pipex_var;
	ap_uint<1> gen219_pipex_var;
	ap_uint<1> gen220_pipex_var;
	ap_uint<1> gen221_pipex_var;
	ap_uint<1> gen222_pipex_var;
	ap_uint<1> gen223_pipex_var;
	ap_uint<1> gen224_pipex_var;
	ap_uint<1> gen225_pipex_var;
	ap_uint<1> gen226_pipex_var;
	ap_uint<1> gen227_pipex_var;
	ap_uint<1> gen228_pipex_var;
	ap_uint<1> gen229_pipex_var;
	ap_uint<1> gen230_pipex_var;
	ap_uint<1> gen231_pipex_var;
	ap_uint<1> gen232_pipex_var;
	ap_uint<1> gen233_pipex_var;
	ap_uint<1> gen234_pipex_var;
	ap_uint<34> gen235_pipex_var;
	ap_uint<34> gen236_pipex_var;
	ap_uint<33> gen237_pipex_var;
	ap_uint<33> gen238_pipex_var;
	ap_uint<33> gen239_pipex_var;
	ap_uint<64> gen240_pipex_var;
	ap_uint<64> gen241_pipex_var;
	ap_uint<32> gen242_pipex_var;
	ap_uint<1> gen243_pipex_var;
	ap_uint<64> gen244_pipex_var;
	ap_uint<64> gen245_pipex_var;
	ap_uint<33> gen246_pipex_var;
	ap_uint<33> gen247_pipex_var;
	ap_uint<33> gen248_pipex_var;
	ap_uint<1> gen249_pipex_var;
	ap_uint<1> gen250_pipex_var;
	ap_uint<1> gen251_pipex_var;
	ap_uint<1> gen252_pipex_var;
	ap_uint<1> gen253_pipex_var;
	ap_uint<1> gen254_pipex_var;
	ap_uint<1> gen255_pipex_var;
	ap_uint<1> gen256_pipex_var;
	ap_uint<1> gen257_pipex_var;
	ap_uint<1> gen258_pipex_var;
	ap_uint<1> gen259_pipex_var;
	ap_uint<1> gen260_pipex_var;
	ap_uint<33> gen261_pipex_var;
	ap_uint<1> gen262_pipex_var;
	ap_uint<1> gen263_pipex_var;
	ap_uint<1> gen264_pipex_var;
	ap_uint<1> gen265_pipex_var;
	ap_uint<1> gen266_pipex_var;
	ap_uint<1> gen267_pipex_var;
	ap_uint<1> gen268_pipex_var;
	ap_uint<1> gen269_pipex_var;
	ap_uint<1> gen270_pipex_var;
	ap_uint<1> gen271_pipex_var;
	ap_uint<1> gen272_pipex_var;
	ap_uint<1> gen273_pipex_var;
	ap_uint<1> gen274_pipex_var;
	ap_uint<1> gen275_pipex_var;
	ap_uint<1> gen276_pipex_var;
	ap_uint<1> gen277_pipex_var;
	ap_uint<1> gen278_pipex_var;
	ap_uint<1> gen279_pipex_var;
	ap_uint<1> gen280_pipex_var;
	ap_uint<1> gen281_pipex_var;
	ap_uint<1> gen282_pipex_var;
	ap_uint<1> gen283_pipex_var;
	ap_uint<1> gen284_pipex_var;
	ap_uint<1> gen285_pipex_var;
	ap_uint<1> gen286_pipex_var;
	ap_uint<1> gen287_pipex_var;
	ap_uint<1> gen288_pipex_var;
	ap_uint<8> gen289_pipex_var;
	ap_uint<1> gen290_pipex_var;
	ap_uint<32> gen291_pipex_var;
	ap_uint<1> gen292_pipex_var;
	ap_uint<32> gen293_pipex_var;
	ap_uint<1> gen294_pipex_var;
	ap_uint<1> gen295_pipex_var;
	ap_uint<1> gen296_pipex_var;
	ap_uint<16> gen297_pipex_var;
	ap_uint<1> gen298_pipex_var;
	ap_uint<32> gen299_pipex_var;
	ap_uint<1> gen300_pipex_var;
	ap_uint<32> gen301_pipex_var;
	ap_uint<1> gen302_pipex_var;
	ap_uint<1> gen303_pipex_var;
	ap_uint<1> gen304_pipex_var;
	ap_uint<1> gen305_pipex_var;
	ap_uint<1> gen306_pipex_var;
	ap_uint<1> gen307_pipex_var;
	ap_uint<1> gen308_pipex_var;
	ap_uint<1> gen309_pipex_var;
	ap_uint<32> gen310_pipex_mcopipe_rdata;
	ap_uint<32> gen311_pipex_mcopipe_rdata;
	ap_uint<32> gen312_pipex_mcopipe_rdata;
	ap_uint<32> gen313_pipex_mcopipe_rdata;
	genpmodule_riscv_1stage_genmcopipe_instr_mem_genstruct_fifo_wdata gen314_pipex_req_struct;
	genpmodule_riscv_1stage_genmcopipe_coproc_M_if_genstruct_fifo_wdata gen315_pipex_req_struct;
	genpmodule_riscv_1stage_genmcopipe_coproc_custom0_if_genstruct_fifo_wdata gen316_pipex_req_struct;
	genpmodule_riscv_1stage_genmcopipe_data_mem_genstruct_fifo_wdata gen317_pipex_req_struct;
	ap_uint<1> gen180_cyclix_var;
	ap_uint<1> gen181_cyclix_var;
	ap_uint<1> gen182_cyclix_var;
	ap_uint<1> gen183_cyclix_var;
	ap_uint<1> gen184_cyclix_var;
	ap_uint<1> gen185_cyclix_var;
	ap_uint<1> gen186_cyclix_var;
	ap_uint<1> gen187_cyclix_var;
	ap_uint<1> gen188_cyclix_var;
	ap_uint<1> gen189_cyclix_var;
	ap_uint<1> gen190_cyclix_var;
	ap_uint<1> gen191_cyclix_var;
	ap_uint<1> gen192_cyclix_var;
	ap_uint<1> gen193_cyclix_var;
	ap_uint<1> gen194_cyclix_var;
	ap_uint<1> gen195_cyclix_var;
	ap_uint<1> gen196_cyclix_var;
	ap_uint<1> gen197_cyclix_var;
	ap_uint<1> gen198_cyclix_var;
	ap_uint<1> gen199_cyclix_var;
	ap_uint<1> gen200_cyclix_var;
	ap_uint<1> gen201_cyclix_var;
	ap_uint<1> gen202_cyclix_var;
	ap_uint<1> gen203_cyclix_var;
	ap_uint<1> gen204_cyclix_var;
	ap_uint<1> gen205_cyclix_var;
	ap_uint<1> gen206_cyclix_var;
	ap_uint<1> gen207_cyclix_var;
	ap_uint<1> gen208_cyclix_var;
	ap_uint<1> gen209_cyclix_var;
	ap_uint<1> gen210_cyclix_var;
	ap_uint<1> gen211_cyclix_var;
	ap_uint<1> gen212_cyclix_var;
	ap_uint<1> gen213_cyclix_var;
	ap_uint<1> gen214_cyclix_var;
	ap_uint<1> gen215_cyclix_var;
	ap_uint<1> gen216_cyclix_var;
	ap_uint<1> gen217_cyclix_var;
	ap_uint<1> gen218_cyclix_var;
	ap_uint<1> gen219_cyclix_var;
	ap_uint<1> gen220_cyclix_var;
	ap_uint<1> gen221_cyclix_var;
	ap_uint<1> gen222_cyclix_var;
	ap_uint<1> gen223_cyclix_var;
	ap_uint<1> gen224_cyclix_var;
	ap_uint<1> gen225_cyclix_var;
	ap_uint<1> gen226_cyclix_var;
	ap_uint<1> gen227_cyclix_var;
	ap_uint<1> gen228_cyclix_var;
	ap_uint<1> gen229_cyclix_var;
	ap_uint<1> gen230_cyclix_var;
	ap_uint<1> gen231_cyclix_var;
	ap_uint<1> gen232_cyclix_var;
	ap_uint<1> gen233_cyclix_var;
	ap_uint<1> gen234_cyclix_var;
	ap_uint<1> gen235_cyclix_var;
	ap_uint<1> gen236_cyclix_var;
	ap_uint<1> gen237_cyclix_var;
	ap_uint<1> gen238_cyclix_var;
	ap_uint<1> gen239_cyclix_var;
	ap_uint<1> gen240_cyclix_var;
	ap_uint<1> gen241_cyclix_var;
	ap_uint<1> gen242_cyclix_var;
	ap_uint<32> gen243_cyclix_var [32];
	ap_uint<1> gen244_cyclix_var;
	ap_uint<1> gen245_cyclix_var;
	ap_uint<1> gen246_cyclix_var;
	ap_uint<1> gen247_cyclix_var;
	ap_uint<1> gen248_cyclix_var;
	ap_uint<1> gen249_cyclix_var;
	ap_uint<1> gen250_cyclix_var;
	ap_uint<1> gen251_cyclix_var;
	ap_uint<1> gen252_cyclix_var;
	ap_uint<1> gen253_cyclix_var;
	ap_uint<1> gen254_cyclix_var;
	ap_uint<1> gen255_cyclix_var;
	ap_uint<1> gen256_cyclix_var;
	ap_uint<1> gen257_cyclix_var;
	ap_uint<1> gen258_cyclix_var;
	ap_uint<1> gen259_cyclix_var;
	ap_uint<1> gen260_cyclix_var;
	ap_uint<1> gen261_cyclix_var;
	ap_uint<1> gen262_cyclix_var;
	ap_uint<1> gen263_cyclix_var;
	ap_uint<1> gen264_cyclix_var;
	ap_uint<1> gen265_cyclix_var;
	ap_uint<1> gen266_cyclix_var;
	ap_uint<1> gen267_cyclix_var;
	ap_uint<1> gen268_cyclix_var;
	ap_uint<1> gen269_cyclix_var;
	ap_uint<1> gen270_cyclix_var;
	ap_uint<1> gen271_cyclix_var;
	ap_uint<1> gen272_cyclix_var;
	ap_uint<1> gen273_cyclix_var;
	ap_uint<1> gen274_cyclix_var;
	ap_uint<1> gen275_cyclix_var;
	ap_uint<1> gen276_cyclix_var;
	ap_uint<1> gen277_cyclix_var;
	ap_uint<1> gen278_cyclix_var;
	ap_uint<1> gen279_cyclix_var;
	ap_uint<1> gen280_cyclix_var;
	ap_uint<1> gen281_cyclix_var;
	ap_uint<1> gen282_cyclix_var;
	ap_uint<1> gen283_cyclix_var;
	ap_uint<1> gen284_cyclix_var;
	ap_uint<1> gen285_cyclix_var;
	ap_uint<1> gen286_cyclix_var;
	ap_uint<1> gen287_cyclix_var;
	ap_uint<1> gen288_cyclix_var;
	ap_uint<1> gen289_cyclix_var;
	ap_uint<1> gen290_cyclix_var;
	ap_uint<1> gen291_cyclix_var;
	ap_uint<1> gen292_cyclix_var;
	ap_uint<1> gen293_cyclix_var;
	ap_uint<1> gen294_cyclix_var;
	ap_uint<1> gen295_cyclix_var;
	ap_uint<1> gen296_cyclix_var;
	ap_uint<1> gen297_cyclix_var;
	ap_uint<1> gen298_cyclix_var;
	ap_uint<1> gen299_cyclix_var;
	ap_uint<1> gen300_cyclix_var;
	ap_uint<1> gen301_cyclix_var;
	ap_uint<1> gen302_cyclix_var;
	ap_uint<1> gen303_cyclix_var;
	ap_uint<1> gen304_cyclix_var;
	ap_uint<1> gen305_cyclix_var;
	ap_uint<1> gen306_cyclix_var;
	ap_uint<1> gen307_cyclix_var;
	ap_uint<1> gen308_cyclix_var;
	ap_uint<1> gen309_cyclix_var;
	ap_uint<1> gen310_cyclix_var;
	ap_uint<1> gen311_cyclix_var;
	ap_uint<1> gen312_cyclix_var;
	ap_uint<1> gen313_cyclix_var;
	ap_uint<1> gen314_cyclix_var;
	ap_uint<1> gen315_cyclix_var;
	ap_uint<1> gen316_cyclix_var;
	ap_uint<1> gen317_cyclix_var;
	ap_uint<1> gen318_cyclix_var;
	ap_uint<1> gen319_cyclix_var;
	ap_uint<1> gen320_cyclix_var;
	ap_uint<1> gen321_cyclix_var;
	ap_uint<1> gen322_cyclix_var;
	ap_uint<1> gen323_cyclix_var;
	ap_uint<1> gen324_cyclix_var;
	ap_uint<1> gen325_cyclix_var;
	ap_uint<1> gen326_cyclix_var;
	ap_uint<1> gen327_cyclix_var;
	ap_uint<1> gen328_cyclix_var;
	ap_uint<1> gen329_cyclix_var;
	ap_uint<1> gen330_cyclix_var;
	ap_uint<1> gen331_cyclix_var;
	ap_uint<1> gen332_cyclix_var;
	ap_uint<1> gen333_cyclix_var;
	ap_uint<1> gen334_cyclix_var;
	ap_uint<1> gen335_cyclix_var;
	ap_uint<1> gen336_cyclix_var;
	ap_uint<1> gen337_cyclix_var;
	ap_uint<1> gen338_cyclix_var;
	ap_uint<1> gen339_cyclix_var;
	ap_uint<1> gen340_cyclix_var;
	ap_uint<1> gen341_cyclix_var;
	ap_uint<1> gen342_cyclix_var;
	ap_uint<1> gen343_cyclix_var;
	ap_uint<1> gen344_cyclix_var;
	ap_uint<1> gen345_cyclix_var;
	ap_uint<1> gen346_cyclix_var;
	ap_uint<1> gen347_cyclix_var;
	ap_uint<1> gen348_cyclix_var;
	ap_uint<1> gen349_cyclix_var;
	ap_uint<1> gen350_cyclix_var;
	ap_uint<1> gen351_cyclix_var;
	ap_uint<1> gen352_cyclix_var;
	ap_uint<1> gen353_cyclix_var;
	ap_uint<1> gen354_cyclix_var;
	ap_uint<1> gen355_cyclix_var;
	ap_uint<1> gen356_cyclix_var;
	ap_uint<1> gen357_cyclix_var;
	ap_uint<1> gen358_cyclix_var;
	ap_uint<1> gen359_cyclix_var;

	if (geninit) {
		genpsticky_glbl_pc = ap_uint<32>(512);
		genpsticky_glbl_regfile[1] = ap_uint<32>(0);
		genpsticky_glbl_regfile[2] = ap_uint<32>(0);
		genpsticky_glbl_regfile[3] = ap_uint<32>(0);
		genpsticky_glbl_regfile[4] = ap_uint<32>(0);
		genpsticky_glbl_regfile[5] = ap_uint<32>(0);
		genpsticky_glbl_regfile[6] = ap_uint<32>(0);
		genpsticky_glbl_regfile[7] = ap_uint<32>(0);
		genpsticky_glbl_regfile[8] = ap_uint<32>(0);
		genpsticky_glbl_regfile[9] = ap_uint<32>(0);
		genpsticky_glbl_regfile[10] = ap_uint<32>(0);
		genpsticky_glbl_regfile[11] = ap_uint<32>(0);
		genpsticky_glbl_regfile[12] = ap_uint<32>(0);
		genpsticky_glbl_regfile[13] = ap_uint<32>(0);
		genpsticky_glbl_regfile[14] = ap_uint<32>(0);
		genpsticky_glbl_regfile[15] = ap_uint<32>(0);
		genpsticky_glbl_regfile[16] = ap_uint<32>(0);
		genpsticky_glbl_regfile[17] = ap_uint<32>(0);
		genpsticky_glbl_regfile[18] = ap_uint<32>(0);
		genpsticky_glbl_regfile[19] = ap_uint<32>(0);
		genpsticky_glbl_regfile[20] = ap_uint<32>(0);
		genpsticky_glbl_regfile[21] = ap_uint<32>(0);
		genpsticky_glbl_regfile[22] = ap_uint<32>(0);
		genpsticky_glbl_regfile[23] = ap_uint<32>(0);
		genpsticky_glbl_regfile[24] = ap_uint<32>(0);
		genpsticky_glbl_regfile[25] = ap_uint<32>(0);
		genpsticky_glbl_regfile[26] = ap_uint<32>(0);
		genpsticky_glbl_regfile[27] = ap_uint<32>(0);
		genpsticky_glbl_regfile[28] = ap_uint<32>(0);
		genpsticky_glbl_regfile[29] = ap_uint<32>(0);
		genpsticky_glbl_regfile[30] = ap_uint<32>(0);
		genpsticky_glbl_regfile[31] = ap_uint<32>(0);
		genpsticky_glbl_jump_req_cmd = ap_uint<32>(0);
		genpsticky_glbl_jump_vector_cmd = ap_uint<32>(0);
		genpsticky_glbl_CSR_MCAUSE = ap_uint<32>(0);
		genpsticky_glbl_MIRQEN = ap_uint<32>(1);
		genpsticky_glbl_MRETADDR = ap_uint<32>(0);
		genmcopipe_instr_mem_wr_done = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_done = ap_uint<32>(0);
		genmcopipe_instr_mem_full_flag = ap_uint<32>(0);
		genmcopipe_instr_mem_empty_flag = ap_uint<32>(1);
		genmcopipe_instr_mem_wr_ptr = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_ptr = ap_uint<32>(0);
		genmcopipe_data_mem_wr_done = ap_uint<32>(0);
		genmcopipe_data_mem_rd_done = ap_uint<32>(0);
		genmcopipe_data_mem_full_flag = ap_uint<32>(0);
		genmcopipe_data_mem_empty_flag = ap_uint<32>(1);
		genmcopipe_data_mem_wr_ptr = ap_uint<32>(0);
		genmcopipe_data_mem_rd_ptr = ap_uint<32>(0);
		genmcopipe_coproc_M_if_wr_done = ap_uint<32>(0);
		genmcopipe_coproc_M_if_rd_done = ap_uint<32>(0);
		genmcopipe_coproc_M_if_full_flag = ap_uint<32>(0);
		genmcopipe_coproc_M_if_empty_flag = ap_uint<32>(1);
		genmcopipe_coproc_M_if_wr_ptr = ap_uint<32>(0);
		genmcopipe_coproc_M_if_rd_ptr = ap_uint<32>(0);
		genmcopipe_coproc_custom0_if_wr_done = ap_uint<32>(0);
		genmcopipe_coproc_custom0_if_rd_done = ap_uint<32>(0);
		genmcopipe_coproc_custom0_if_full_flag = ap_uint<32>(0);
		genmcopipe_coproc_custom0_if_empty_flag = ap_uint<32>(1);
		genmcopipe_coproc_custom0_if_wr_ptr = ap_uint<32>(0);
		genmcopipe_coproc_custom0_if_rd_ptr = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF_COUNTER = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
		genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(0);

	} else {
gen243_cyclix_var = genpsticky_glbl_regfile;
		// mcopipe processing
		genmcopipe_instr_mem_wr_done = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_done = ap_uint<32>(0);
		genmcopipe_instr_mem_wr_ptr_next = (genmcopipe_instr_mem_wr_ptr + ap_uint<32>(1));
		genmcopipe_instr_mem_rd_ptr_next = (genmcopipe_instr_mem_rd_ptr + ap_uint<32>(1));
		genmcopipe_data_mem_wr_done = ap_uint<32>(0);
		genmcopipe_data_mem_rd_done = ap_uint<32>(0);
		genmcopipe_data_mem_wr_ptr_next = (genmcopipe_data_mem_wr_ptr + ap_uint<32>(1));
		genmcopipe_data_mem_rd_ptr_next = (genmcopipe_data_mem_rd_ptr + ap_uint<32>(1));
		genmcopipe_coproc_M_if_wr_done = ap_uint<32>(0);
		genmcopipe_coproc_M_if_rd_done = ap_uint<32>(0);
		genmcopipe_coproc_M_if_wr_ptr_next = (genmcopipe_coproc_M_if_wr_ptr + ap_uint<32>(1));
		genmcopipe_coproc_M_if_rd_ptr_next = (genmcopipe_coproc_M_if_rd_ptr + ap_uint<32>(1));
		genmcopipe_coproc_custom0_if_wr_done = ap_uint<32>(0);
		genmcopipe_coproc_custom0_if_rd_done = ap_uint<32>(0);
		genmcopipe_coproc_custom0_if_wr_ptr_next = (genmcopipe_coproc_custom0_if_wr_ptr + ap_uint<32>(1));
		genmcopipe_coproc_custom0_if_rd_ptr_next = (genmcopipe_coproc_custom0_if_rd_ptr + ap_uint<32>(1));
		// logic of stages
		// #### Stage processing: EXEC ####
		genpstage_EXEC_genctrl_succ = ap_uint<32>(0);
		genpstage_EXEC_genctrl_working = ap_uint<32>(0);
		gen180_cyclix_var = genpstage_EXEC_genctrl_stalled_glbl;
		if (gen180_cyclix_var) {
			genpstage_EXEC_genctrl_new = ap_uint<32>(0);
			genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_EXEC_genctrl_active = ap_uint<32>(1);
		}
		gen181_cyclix_var = ap_uint<1>(0);
		gen181_cyclix_var = (gen181_cyclix_var || gen180_cyclix_var);
		gen181_cyclix_var = !gen181_cyclix_var;
		if (gen181_cyclix_var) {
			genpstage_EXEC_genctrl_active = ap_uint<32>(1);
			genpstage_EXEC_genctrl_new = genpstage_EXEC_genctrl_active;
		}
		genpstage_EXEC_genctrl_occupied = genpstage_EXEC_genctrl_active;
		genpstage_EXEC_genctrl_finish = ap_uint<32>(0);
		genpstage_EXEC_genpctrl_flushreq = ap_uint<32>(0);
		gen182_cyclix_var = genpstage_EXEC_genctrl_occupied;
		if (gen182_cyclix_var) {
			// Initializing new newaccums descriptors ####
			gen183_cyclix_var = genpstage_EXEC_genctrl_new;
			if (gen183_cyclix_var) {
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
			}
			// Fetching locals from src_glbls
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].instr_req_done;
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = '{default:ap_uint<32>(0)};
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].irq_mcause;
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].irq_recv;
			genpstage_EXEC_TRX_LOCAL = '{default:ap_uint<32>(0)};
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].Ext_coproc_req_done;
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].jump_req_done;
			genpstage_EXEC_TRX_LOCAL = '{default:ap_uint<32>(0)};
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].data_req_done;
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			// Acquiring mcopipe rdata
			gen184_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.rdreq_pending;
			if (gen184_cyclix_var) {
				gen185_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.if_id == ap_uint<1>(0));
				gen186_cyclix_var = gen185_cyclix_var;
				if (gen186_cyclix_var) {
					gen187_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.tid == genmcopipe_instr_mem_rd_ptr);
					gen188_cyclix_var = gen187_cyclix_var;
					if (gen188_cyclix_var) {
						gen189_cyclix_var = genmcopipe_instr_mem_resp.read_nb(gen310_pipex_mcopipe_rdata);
						gen190_cyclix_var = gen189_cyclix_var;
						if (gen190_cyclix_var) {
							genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = ap_uint<32>(1);
							genpstage_EXEC_TRX_BUF = gen310_pipex_mcopipe_rdata;
							genmcopipe_instr_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			gen191_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.rdreq_pending;
			if (gen191_cyclix_var) {
				gen192_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.if_id == ap_uint<1>(0));
				gen193_cyclix_var = gen192_cyclix_var;
				if (gen193_cyclix_var) {
					gen194_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.tid == genmcopipe_coproc_M_if_rd_ptr);
					gen195_cyclix_var = gen194_cyclix_var;
					if (gen195_cyclix_var) {
						gen196_cyclix_var = genmcopipe_coproc_M_if_resp.read_nb(gen311_pipex_mcopipe_rdata);
						gen197_cyclix_var = gen196_cyclix_var;
						if (gen197_cyclix_var) {
							genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = ap_uint<32>(1);
							genpstage_EXEC_TRX_BUF = gen311_pipex_mcopipe_rdata;
							genmcopipe_coproc_M_if_rd_done = ap_uint<32>(1);
						}
					}
				}
				gen198_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.if_id == ap_uint<1>(1));
				gen199_cyclix_var = gen198_cyclix_var;
				if (gen199_cyclix_var) {
					gen200_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.tid == genmcopipe_coproc_custom0_if_rd_ptr);
					gen201_cyclix_var = gen200_cyclix_var;
					if (gen201_cyclix_var) {
						gen202_cyclix_var = genmcopipe_coproc_custom0_if_resp.read_nb(gen312_pipex_mcopipe_rdata);
						gen203_cyclix_var = gen202_cyclix_var;
						if (gen203_cyclix_var) {
							genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = ap_uint<32>(1);
							genpstage_EXEC_TRX_BUF = gen312_pipex_mcopipe_rdata;
							genmcopipe_coproc_custom0_if_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			gen204_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.rdreq_pending;
			if (gen204_cyclix_var) {
				gen205_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.if_id == ap_uint<1>(0));
				gen206_cyclix_var = gen205_cyclix_var;
				if (gen206_cyclix_var) {
					gen207_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.tid == genmcopipe_data_mem_rd_ptr);
					gen208_cyclix_var = gen207_cyclix_var;
					if (gen208_cyclix_var) {
						gen209_cyclix_var = genmcopipe_data_mem_resp.read_nb(gen313_pipex_mcopipe_rdata);
						gen210_cyclix_var = gen209_cyclix_var;
						if (gen210_cyclix_var) {
							genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = ap_uint<32>(1);
							genpstage_EXEC_TRX_BUF = gen313_pipex_mcopipe_rdata;
							genmcopipe_data_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			// Pipeline flush processing
			gen211_cyclix_var = genpstage_EXEC_genpctrl_flushreq;
			if (gen211_cyclix_var) {
			}
		}
		// Saving succ targets
		gen155_pipex_succbuf = genpsticky_glbl_pc;
		// Generating payload
		gen156_pipex_var = genpsticky_glbl_jump_req_cmd;
		gen212_cyclix_var = gen156_pipex_var;
		if (gen212_cyclix_var) {
			gen213_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen213_cyclix_var) {
				genpsticky_glbl_pc = genpsticky_glbl_jump_vector_cmd;
			}
			gen214_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen214_cyclix_var) {
				genpsticky_glbl_jump_req_cmd = ap_uint<32>(0);
			}
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			gen215_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen215_cyclix_var) {
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
			}
		}
		genpstage_EXEC_TRX_LOCAL = genpsticky_glbl_pc;
		gen157_pipex_var = (genpstage_EXEC_TRX_LOCAL.curinstr_addr + ap_uint<32>(4));
		genpstage_EXEC_TRX_LOCAL = gen157_pipex_var;
		gen154_pipex_succreq = ap_uint<32>(1);
		gen155_pipex_succbuf = genpstage_EXEC_TRX_LOCAL.nextinstr_addr;
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstr_addr;
		genpstage_EXEC_TRX_LOCAL = ap_uint<32>(15);
		genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
		gen158_pipex_var = ~genpstage_EXEC_TRX_LOCAL.instr_req_done;
		gen159_pipex_var = gen158_pipex_var;
		gen216_cyclix_var = gen159_pipex_var;
		if (gen216_cyclix_var) {
			gen217_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen217_cyclix_var) {
				gen218_cyclix_var = ~genmcopipe_instr_mem_full_flag;
				gen219_cyclix_var = gen218_cyclix_var;
				if (gen219_cyclix_var) {
					gen314_pipex_req_struct = ap_uint<1>(0);
					gen314_pipex_req_struct = genpstage_EXEC_TRX_LOCAL.instr_busreq;
					gen220_cyclix_var = genmcopipe_instr_mem_req.write_nb(gen314_pipex_req_struct);
					gen221_cyclix_var = gen220_cyclix_var;
					if (gen221_cyclix_var) {
						gen160_pipex_var = ap_uint<32>(1);
						gen222_cyclix_var = !ap_uint<1>(0);
						genpstage_EXEC_TRX_BUF = gen222_cyclix_var;
						genpstage_EXEC_TRX_BUF = genmcopipe_instr_mem_wr_ptr;
						genpstage_EXEC_TRX_BUF = ap_uint<1>(0);
						gen223_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.rdreq_pending;
						if (gen223_cyclix_var) {
							genmcopipe_instr_mem_wr_done = ap_uint<32>(1);
						}
					}
				}
			}
			genpstage_EXEC_TRX_LOCAL = gen160_pipex_var;
			gen224_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen224_cyclix_var) {
				genpstage_EXEC_TRX_BUF = gen160_pipex_var;
			}
		}
		gen161_pipex_var = ~genpstage_EXEC_TRX_LOCAL.instr_req_done;
		gen162_pipex_var = gen161_pipex_var;
		gen225_cyclix_var = gen162_pipex_var;
		if (gen225_cyclix_var) {
			gen226_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen226_cyclix_var) {
				genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
			}
			genpstage_EXEC_genctrl_active = ap_uint<32>(0);
		}
		gen227_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.resp_done;
		if (gen227_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.rdata;
		}
		gen163_pipex_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.resp_done;
		gen164_pipex_var = ~gen163_pipex_var;
		gen165_pipex_var = gen164_pipex_var;
		gen228_cyclix_var = gen165_pipex_var;
		if (gen228_cyclix_var) {
			gen229_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen229_cyclix_var) {
				genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
			}
			genpstage_EXEC_genctrl_active = ap_uint<32>(0);
		}
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[6:0];
		genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[19:15];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[24:20];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[11:7];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[14:12];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[31:25];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[24:20];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[27:24];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[23:20];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[31:20];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[19:15];
		gen166_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[31:20];
		gen167_pipex_var = gen166_pipex_var[31];
		gen168_pipex_var = gen167_pipex_var.concat((ap_uint<31>)gen167_pipex_var.concat((ap_uint<30>)gen167_pipex_var.concat((ap_uint<29>)gen167_pipex_var.concat((ap_uint<28>)gen167_pipex_var.concat((ap_uint<27>)gen167_pipex_var.concat((ap_uint<26>)gen167_pipex_var.concat((ap_uint<25>)gen167_pipex_var.concat((ap_uint<24>)gen167_pipex_var.concat((ap_uint<23>)gen167_pipex_var.concat((ap_uint<22>)gen167_pipex_var.concat((ap_uint<21>)gen167_pipex_var.concat((ap_uint<20>)gen167_pipex_var.concat((ap_uint<19>)gen167_pipex_var.concat((ap_uint<18>)gen167_pipex_var.concat((ap_uint<17>)gen167_pipex_var.concat((ap_uint<16>)gen167_pipex_var.concat((ap_uint<15>)gen167_pipex_var.concat((ap_uint<14>)gen167_pipex_var.concat((ap_uint<13>)gen167_pipex_var.concat((ap_uint<12>)genpstage_EXEC_TRX_LOCAL.instr_code[31:20]))))))))))))))))))));
		genpstage_EXEC_TRX_LOCAL = gen168_pipex_var;
		gen169_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[31:25].concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.instr_code[11:7]);
		gen170_pipex_var = gen169_pipex_var[11];
		gen171_pipex_var = gen170_pipex_var.concat((ap_uint<31>)gen170_pipex_var.concat((ap_uint<30>)gen170_pipex_var.concat((ap_uint<29>)gen170_pipex_var.concat((ap_uint<28>)gen170_pipex_var.concat((ap_uint<27>)gen170_pipex_var.concat((ap_uint<26>)gen170_pipex_var.concat((ap_uint<25>)gen170_pipex_var.concat((ap_uint<24>)gen170_pipex_var.concat((ap_uint<23>)gen170_pipex_var.concat((ap_uint<22>)gen170_pipex_var.concat((ap_uint<21>)gen170_pipex_var.concat((ap_uint<20>)gen170_pipex_var.concat((ap_uint<19>)gen170_pipex_var.concat((ap_uint<18>)gen170_pipex_var.concat((ap_uint<17>)gen170_pipex_var.concat((ap_uint<16>)gen170_pipex_var.concat((ap_uint<15>)gen170_pipex_var.concat((ap_uint<14>)gen170_pipex_var.concat((ap_uint<13>)gen170_pipex_var.concat((ap_uint<12>)gen169_pipex_var))))))))))))))))))));
		genpstage_EXEC_TRX_LOCAL = gen171_pipex_var;
		gen172_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[31].concat((ap_uint<12>)genpstage_EXEC_TRX_LOCAL.instr_code[7].concat((ap_uint<11>)genpstage_EXEC_TRX_LOCAL.instr_code[30:25].concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.instr_code[11:8].concat((ap_uint<1>)ap_uint<1>(0)))));
		gen173_pipex_var = gen172_pipex_var[12];
		gen174_pipex_var = gen173_pipex_var.concat((ap_uint<31>)gen173_pipex_var.concat((ap_uint<30>)gen173_pipex_var.concat((ap_uint<29>)gen173_pipex_var.concat((ap_uint<28>)gen173_pipex_var.concat((ap_uint<27>)gen173_pipex_var.concat((ap_uint<26>)gen173_pipex_var.concat((ap_uint<25>)gen173_pipex_var.concat((ap_uint<24>)gen173_pipex_var.concat((ap_uint<23>)gen173_pipex_var.concat((ap_uint<22>)gen173_pipex_var.concat((ap_uint<21>)gen173_pipex_var.concat((ap_uint<20>)gen173_pipex_var.concat((ap_uint<19>)gen173_pipex_var.concat((ap_uint<18>)gen173_pipex_var.concat((ap_uint<17>)gen173_pipex_var.concat((ap_uint<16>)gen173_pipex_var.concat((ap_uint<15>)gen173_pipex_var.concat((ap_uint<14>)gen173_pipex_var.concat((ap_uint<13>)gen172_pipex_var)))))))))))))))))));
		genpstage_EXEC_TRX_LOCAL = gen174_pipex_var;
		gen175_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[31:12].concat((ap_uint<12>)ap_uint<12>(0));
		genpstage_EXEC_TRX_LOCAL = gen175_pipex_var;
		gen176_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[31].concat((ap_uint<20>)genpstage_EXEC_TRX_LOCAL.instr_code[19:12].concat((ap_uint<12>)genpstage_EXEC_TRX_LOCAL.instr_code[20].concat((ap_uint<11>)genpstage_EXEC_TRX_LOCAL.instr_code[30:21].concat((ap_uint<1>)ap_uint<1>(0)))));
		gen177_pipex_var = gen176_pipex_var[20];
		gen178_pipex_var = gen177_pipex_var.concat((ap_uint<31>)gen177_pipex_var.concat((ap_uint<30>)gen177_pipex_var.concat((ap_uint<29>)gen177_pipex_var.concat((ap_uint<28>)gen177_pipex_var.concat((ap_uint<27>)gen177_pipex_var.concat((ap_uint<26>)gen177_pipex_var.concat((ap_uint<25>)gen177_pipex_var.concat((ap_uint<24>)gen177_pipex_var.concat((ap_uint<23>)gen177_pipex_var.concat((ap_uint<22>)gen177_pipex_var.concat((ap_uint<21>)gen176_pipex_var)))))))))));
		genpstage_EXEC_TRX_LOCAL = gen178_pipex_var;
		switch (genpstage_EXEC_TRX_LOCAL) {
			case 55:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_U;
				break;
			case 23:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_U;
				break;
			case 111:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(4);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_J;
				break;
			case 103:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(4);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_I;
				break;
			case 99:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_B;
				gen179_pipex_var = (genpstage_EXEC_TRX_LOCAL.funct3 == ap_uint<32>(6));
				gen180_pipex_var = (genpstage_EXEC_TRX_LOCAL.funct3 == ap_uint<32>(7));
				gen181_pipex_var = (gen179_pipex_var | gen180_pipex_var);
				gen182_pipex_var = gen181_pipex_var;
				gen230_cyclix_var = gen182_pipex_var;
				if (gen230_cyclix_var) {
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				}
				break;
			case 3:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(5);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_I;
				break;
			case 35:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_S;
				break;
			case 19:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_I;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				switch (genpstage_EXEC_TRX_LOCAL) {
					case 0:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 1:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(4);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						gen183_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.instr_code[24:20]);
						genpstage_EXEC_TRX_LOCAL = gen183_pipex_var;
						break;
					case 2:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 4:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(7);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 5:
						gen184_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[30];
						gen231_cyclix_var = gen184_pipex_var;
						if (gen231_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						}
						gen185_pipex_var = ap_uint<1>(0);
						gen185_pipex_var = (gen185_pipex_var || gen184_pipex_var);
						gen185_pipex_var = !gen185_pipex_var;
						gen232_cyclix_var = gen185_pipex_var;
						if (gen232_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(5);
						}
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						gen186_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.instr_code[24:20]);
						genpstage_EXEC_TRX_LOCAL = gen186_pipex_var;
						break;
					case 6:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(3);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 7:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
				}
				break;
			case 51:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				switch (genpstage_EXEC_TRX_LOCAL) {
					case 0:
						gen187_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[30];
						gen233_cyclix_var = gen187_pipex_var;
						if (gen233_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						}
						gen188_pipex_var = ap_uint<1>(0);
						gen188_pipex_var = (gen188_pipex_var || gen187_pipex_var);
						gen188_pipex_var = !gen188_pipex_var;
						gen234_cyclix_var = gen188_pipex_var;
						if (gen234_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
						}
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 1:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(4);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 2:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 4:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(7);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 5:
						gen189_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[30];
						gen235_cyclix_var = gen189_pipex_var;
						if (gen235_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						}
						gen190_pipex_var = ap_uint<1>(0);
						gen190_pipex_var = (gen190_pipex_var || gen189_pipex_var);
						gen190_pipex_var = !gen190_pipex_var;
						gen236_cyclix_var = gen190_pipex_var;
						if (gen236_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(5);
						}
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 6:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(3);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 7:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
				}
				gen191_pipex_var = (genpstage_EXEC_TRX_LOCAL.funct7 == ap_uint<32>(1));
				gen192_pipex_var = gen191_pipex_var;
				gen237_cyclix_var = gen192_pipex_var;
				if (gen237_cyclix_var) {
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(7);
				}
				break;
			case 15:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
			case 115:
				switch (genpstage_EXEC_TRX_LOCAL) {
					case 0:
						gen193_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[20];
						gen238_cyclix_var = gen193_pipex_var;
						if (gen238_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						}
						gen194_pipex_var = ap_uint<1>(0);
						gen194_pipex_var = (gen194_pipex_var || gen193_pipex_var);
						gen194_pipex_var = !gen194_pipex_var;
						gen239_cyclix_var = gen194_pipex_var;
						if (gen239_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						}
						break;
					case 1:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 2:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(3);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(8);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 5:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						gen195_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.zimm);
						genpstage_EXEC_TRX_LOCAL = gen195_pipex_var;
						break;
					case 6:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(8);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						gen196_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.zimm);
						genpstage_EXEC_TRX_LOCAL = gen196_pipex_var;
						break;
					case 7:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(8);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						gen197_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.zimm);
						genpstage_EXEC_TRX_LOCAL = gen197_pipex_var;
						break;
				}
				break;
			case 11:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(7);
				break;
		}
		gen198_pipex_var = genpstage_EXEC_TRX_LOCAL.mem_req;
		gen240_cyclix_var = gen198_pipex_var;
		if (gen240_cyclix_var) {
			switch (genpstage_EXEC_TRX_LOCAL) {
				case 0:
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
					break;
				case 1:
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(3);
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
					break;
				case 2:
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(15);
					break;
				case 4:
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
					break;
				case 5:
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(3);
					break;
			}
		}
		gen199_pipex_var = (genpstage_EXEC_TRX_LOCAL.instr_code == ap_uint<32>(807403635));
		gen200_pipex_var = gen199_pipex_var;
		gen241_cyclix_var = gen200_pipex_var;
		if (gen241_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = genpsticky_glbl_MRETADDR;
		}
		gen201_pipex_var = (genpstage_EXEC_TRX_LOCAL.rd_addr == ap_uint<32>(0));
		gen202_pipex_var = gen201_pipex_var;
		gen242_cyclix_var = gen202_pipex_var;
		if (gen242_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
		}
		gen203_pipex_var = gen63_cyclix_readPrev[1];
		gen203_pipex_var = gen63_cyclix_readPrev[2];
		gen203_pipex_var = gen63_cyclix_readPrev[3];
		gen203_pipex_var = gen63_cyclix_readPrev[4];
		gen203_pipex_var = gen63_cyclix_readPrev[5];
		gen203_pipex_var = gen63_cyclix_readPrev[6];
		gen203_pipex_var = gen63_cyclix_readPrev[7];
		gen203_pipex_var = gen63_cyclix_readPrev[8];
		gen203_pipex_var = gen63_cyclix_readPrev[9];
		gen203_pipex_var = gen63_cyclix_readPrev[10];
		gen203_pipex_var = gen63_cyclix_readPrev[11];
		gen203_pipex_var = gen63_cyclix_readPrev[12];
		gen203_pipex_var = gen63_cyclix_readPrev[13];
		gen203_pipex_var = gen63_cyclix_readPrev[14];
		gen203_pipex_var = gen63_cyclix_readPrev[15];
		gen203_pipex_var = gen63_cyclix_readPrev[16];
		gen203_pipex_var = gen63_cyclix_readPrev[17];
		gen203_pipex_var = gen63_cyclix_readPrev[18];
		gen203_pipex_var = gen63_cyclix_readPrev[19];
		gen203_pipex_var = gen63_cyclix_readPrev[20];
		gen203_pipex_var = gen63_cyclix_readPrev[21];
		gen203_pipex_var = gen63_cyclix_readPrev[22];
		gen203_pipex_var = gen63_cyclix_readPrev[23];
		gen203_pipex_var = gen63_cyclix_readPrev[24];
		gen203_pipex_var = gen63_cyclix_readPrev[25];
		gen203_pipex_var = gen63_cyclix_readPrev[26];
		gen203_pipex_var = gen63_cyclix_readPrev[27];
		gen203_pipex_var = gen63_cyclix_readPrev[28];
		gen203_pipex_var = gen63_cyclix_readPrev[29];
		gen203_pipex_var = gen63_cyclix_readPrev[30];
		gen203_pipex_var = gen63_cyclix_readPrev[31];
		genpstage_EXEC_TRX_LOCAL = gen203_pipex_var[genpstage_EXEC_TRX_LOCAL.rs1_addr];
		gen204_pipex_var = gen63_cyclix_readPrev[1];
		gen204_pipex_var = gen63_cyclix_readPrev[2];
		gen204_pipex_var = gen63_cyclix_readPrev[3];
		gen204_pipex_var = gen63_cyclix_readPrev[4];
		gen204_pipex_var = gen63_cyclix_readPrev[5];
		gen204_pipex_var = gen63_cyclix_readPrev[6];
		gen204_pipex_var = gen63_cyclix_readPrev[7];
		gen204_pipex_var = gen63_cyclix_readPrev[8];
		gen204_pipex_var = gen63_cyclix_readPrev[9];
		gen204_pipex_var = gen63_cyclix_readPrev[10];
		gen204_pipex_var = gen63_cyclix_readPrev[11];
		gen204_pipex_var = gen63_cyclix_readPrev[12];
		gen204_pipex_var = gen63_cyclix_readPrev[13];
		gen204_pipex_var = gen63_cyclix_readPrev[14];
		gen204_pipex_var = gen63_cyclix_readPrev[15];
		gen204_pipex_var = gen63_cyclix_readPrev[16];
		gen204_pipex_var = gen63_cyclix_readPrev[17];
		gen204_pipex_var = gen63_cyclix_readPrev[18];
		gen204_pipex_var = gen63_cyclix_readPrev[19];
		gen204_pipex_var = gen63_cyclix_readPrev[20];
		gen204_pipex_var = gen63_cyclix_readPrev[21];
		gen204_pipex_var = gen63_cyclix_readPrev[22];
		gen204_pipex_var = gen63_cyclix_readPrev[23];
		gen204_pipex_var = gen63_cyclix_readPrev[24];
		gen204_pipex_var = gen63_cyclix_readPrev[25];
		gen204_pipex_var = gen63_cyclix_readPrev[26];
		gen204_pipex_var = gen63_cyclix_readPrev[27];
		gen204_pipex_var = gen63_cyclix_readPrev[28];
		gen204_pipex_var = gen63_cyclix_readPrev[29];
		gen204_pipex_var = gen63_cyclix_readPrev[30];
		gen204_pipex_var = gen63_cyclix_readPrev[31];
		genpstage_EXEC_TRX_LOCAL = gen204_pipex_var[genpstage_EXEC_TRX_LOCAL.rs2_addr];
		gen205_pipex_var = (genpstage_EXEC_TRX_LOCAL.rs1_addr == ap_uint<32>(0));
		gen206_pipex_var = gen205_pipex_var;
		gen244_cyclix_var = gen206_pipex_var;
		if (gen244_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
		}
		gen207_pipex_var = (genpstage_EXEC_TRX_LOCAL.rs2_addr == ap_uint<32>(0));
		gen208_pipex_var = gen207_pipex_var;
		gen245_cyclix_var = gen208_pipex_var;
		if (gen245_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
		}
		gen209_pipex_var = genpstage_EXEC_TRX_LOCAL.csrreq;
		gen246_cyclix_var = gen209_pipex_var;
		if (gen246_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = genpsticky_glbl_CSR_MCAUSE;
		}
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.rs1_rdata;
		switch (genpstage_EXEC_TRX_LOCAL) {
			case 1:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate;
				break;
			case 2:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstr_addr;
				break;
		}
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.rs2_rdata;
		switch (genpstage_EXEC_TRX_LOCAL) {
			case 1:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate;
				break;
			case 2:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.csr_rdata;
				break;
		}
		gen210_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_unsigned;
		gen247_cyclix_var = gen210_pipex_var;
		if (gen247_cyclix_var) {
			gen211_pipex_var = ap_uint<1>(0).concat((ap_uint<32>)genpstage_EXEC_TRX_LOCAL.alu_op1);
			genpstage_EXEC_TRX_LOCAL = gen211_pipex_var;
			gen212_pipex_var = ap_uint<1>(0).concat((ap_uint<32>)genpstage_EXEC_TRX_LOCAL.alu_op2);
			genpstage_EXEC_TRX_LOCAL = gen212_pipex_var;
		}
		gen213_pipex_var = ap_uint<1>(0);
		gen213_pipex_var = (gen213_pipex_var || gen210_pipex_var);
		gen213_pipex_var = !gen213_pipex_var;
		gen248_cyclix_var = gen213_pipex_var;
		if (gen248_cyclix_var) {
			gen214_pipex_var = genpstage_EXEC_TRX_LOCAL[31];
			gen215_pipex_var = gen214_pipex_var.concat((ap_uint<32>)genpstage_EXEC_TRX_LOCAL.alu_op1);
			genpstage_EXEC_TRX_LOCAL = gen215_pipex_var;
			gen216_pipex_var = genpstage_EXEC_TRX_LOCAL[31];
			gen217_pipex_var = gen216_pipex_var.concat((ap_uint<32>)genpstage_EXEC_TRX_LOCAL.alu_op2);
			genpstage_EXEC_TRX_LOCAL = gen217_pipex_var;
		}
		gen218_pipex_var = genpsticky_glbl_MIRQEN;
		gen249_cyclix_var = gen218_pipex_var;
		if (gen249_cyclix_var) {
			gen219_pipex_var = ~genpstage_EXEC_TRX_LOCAL.irq_recv;
			gen220_pipex_var = gen219_pipex_var;
			gen250_cyclix_var = gen220_pipex_var;
			if (gen250_cyclix_var) {
				gen251_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen251_cyclix_var) {
					gen252_cyclix_var = irq_fifo.read_nb(genpstage_EXEC_TRX_LOCAL);
					gen221_pipex_var = gen252_cyclix_var;
				}
				genpstage_EXEC_TRX_LOCAL = gen221_pipex_var;
				gen253_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen253_cyclix_var) {
					genpstage_EXEC_TRX_BUF = gen221_pipex_var;
				}
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.irq_mcause;
				gen254_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen254_cyclix_var) {
					genpstage_EXEC_TRX_BUF = genpstage_EXEC_TRX_LOCAL.irq_mcause;
				}
			}
			gen222_pipex_var = genpstage_EXEC_TRX_LOCAL.irq_recv;
			gen255_cyclix_var = gen222_pipex_var;
			if (gen255_cyclix_var) {
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(128);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				gen256_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen256_cyclix_var) {
					genpsticky_glbl_MIRQEN = ap_uint<32>(0);
				}
				gen257_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen257_cyclix_var) {
					genpsticky_glbl_CSR_MCAUSE = genpstage_EXEC_TRX_LOCAL.irq_mcause;
				}
				gen258_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen258_cyclix_var) {
					genpsticky_glbl_MRETADDR = genpstage_EXEC_TRX_LOCAL.curinstr_addr;
				}
			}
		}
		gen223_pipex_var = genpstage_EXEC_TRX_LOCAL.mret_req;
		gen259_cyclix_var = gen223_pipex_var;
		if (gen259_cyclix_var) {
			gen260_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen260_cyclix_var) {
				genpsticky_glbl_MIRQEN = ap_uint<32>(1);
			}
		}
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code;
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_op1;
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_op2;
		gen224_pipex_var = ~genpstage_EXEC_TRX_LOCAL.Ext_coproc_req_done;
		gen225_pipex_var = gen224_pipex_var;
		gen261_cyclix_var = gen225_pipex_var;
		if (gen261_cyclix_var) {
			gen226_pipex_var = genpstage_EXEC_TRX_LOCAL.m_ext_req;
			gen262_cyclix_var = gen226_pipex_var;
			if (gen262_cyclix_var) {
				gen263_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen263_cyclix_var) {
					gen264_cyclix_var = ~genmcopipe_coproc_M_if_full_flag;
					gen265_cyclix_var = gen264_cyclix_var;
					if (gen265_cyclix_var) {
						gen315_pipex_req_struct = ap_uint<32>(0);
						gen315_pipex_req_struct = genpstage_EXEC_TRX_LOCAL.Ext_coproc_busreq;
						gen266_cyclix_var = genmcopipe_coproc_M_if_req.write_nb(gen315_pipex_req_struct);
						gen267_cyclix_var = gen266_cyclix_var;
						if (gen267_cyclix_var) {
							gen227_pipex_var = ap_uint<32>(1);
							gen268_cyclix_var = !ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = gen268_cyclix_var;
							genpstage_EXEC_TRX_BUF = genmcopipe_coproc_M_if_wr_ptr;
							genpstage_EXEC_TRX_BUF = ap_uint<1>(0);
							gen269_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.rdreq_pending;
							if (gen269_cyclix_var) {
								genmcopipe_coproc_M_if_wr_done = ap_uint<32>(1);
							}
						}
					}
				}
				genpstage_EXEC_TRX_LOCAL = gen227_pipex_var;
				gen270_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen270_cyclix_var) {
					genpstage_EXEC_TRX_BUF = gen227_pipex_var;
				}
				gen228_pipex_var = ~genpstage_EXEC_TRX_LOCAL.Ext_coproc_req_done;
				gen229_pipex_var = gen228_pipex_var;
				gen271_cyclix_var = gen229_pipex_var;
				if (gen271_cyclix_var) {
					gen272_cyclix_var = genpstage_EXEC_genctrl_active;
					if (gen272_cyclix_var) {
						genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
					}
					genpstage_EXEC_genctrl_active = ap_uint<32>(0);
				}
			}
			gen230_pipex_var = genpstage_EXEC_TRX_LOCAL.custom0_ext_req;
			gen273_cyclix_var = gen230_pipex_var;
			if (gen273_cyclix_var) {
				gen274_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen274_cyclix_var) {
					gen275_cyclix_var = ~genmcopipe_coproc_custom0_if_full_flag;
					gen276_cyclix_var = gen275_cyclix_var;
					if (gen276_cyclix_var) {
						gen316_pipex_req_struct = ap_uint<32>(0);
						gen316_pipex_req_struct = genpstage_EXEC_TRX_LOCAL.Ext_coproc_busreq;
						gen277_cyclix_var = genmcopipe_coproc_custom0_if_req.write_nb(gen316_pipex_req_struct);
						gen278_cyclix_var = gen277_cyclix_var;
						if (gen278_cyclix_var) {
							gen231_pipex_var = ap_uint<32>(1);
							gen279_cyclix_var = !ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = gen279_cyclix_var;
							genpstage_EXEC_TRX_BUF = genmcopipe_coproc_custom0_if_wr_ptr;
							genpstage_EXEC_TRX_BUF = ap_uint<1>(1);
							gen280_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.rdreq_pending;
							if (gen280_cyclix_var) {
								genmcopipe_coproc_custom0_if_wr_done = ap_uint<32>(1);
							}
						}
					}
				}
				genpstage_EXEC_TRX_LOCAL = gen231_pipex_var;
				gen281_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen281_cyclix_var) {
					genpstage_EXEC_TRX_BUF = gen231_pipex_var;
				}
				gen232_pipex_var = ~genpstage_EXEC_TRX_LOCAL.Ext_coproc_req_done;
				gen233_pipex_var = gen232_pipex_var;
				gen282_cyclix_var = gen233_pipex_var;
				if (gen282_cyclix_var) {
					gen283_cyclix_var = genpstage_EXEC_genctrl_active;
					if (gen283_cyclix_var) {
						genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
					}
					genpstage_EXEC_genctrl_active = ap_uint<32>(0);
				}
			}
		}
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_op1_wide;
		gen234_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_req;
		gen284_cyclix_var = gen234_pipex_var;
		if (gen284_cyclix_var) {
			switch (genpstage_EXEC_TRX_LOCAL) {
				case 0:
					gen235_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide + genpstage_EXEC_TRX_LOCAL.alu_op2_wide);
					genpstage_EXEC_TRX_LOCAL = gen235_pipex_var;
					break;
				case 1:
					gen236_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide - genpstage_EXEC_TRX_LOCAL.alu_op2_wide);
					genpstage_EXEC_TRX_LOCAL = gen236_pipex_var;
					break;
				case 2:
					gen237_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide & genpstage_EXEC_TRX_LOCAL.alu_op2_wide);
					genpstage_EXEC_TRX_LOCAL = gen237_pipex_var;
					break;
				case 3:
					gen238_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide | genpstage_EXEC_TRX_LOCAL.alu_op2_wide);
					genpstage_EXEC_TRX_LOCAL = gen238_pipex_var;
					break;
				case 4:
					gen239_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide << genpstage_EXEC_TRX_LOCAL.alu_op2_wide);
					genpstage_EXEC_TRX_LOCAL = gen239_pipex_var;
					break;
				case 5:
					gen240_pipex_var = ap_uint<32>(0).concat((ap_uint<32>)genpstage_EXEC_TRX_LOCAL.alu_op1_wide[31:0]);
					gen241_pipex_var = (gen240_pipex_var >> genpstage_EXEC_TRX_LOCAL.alu_op2_wide[4:0]);
					genpstage_EXEC_TRX_LOCAL = gen241_pipex_var;
					break;
				case 6:
					gen242_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_op1_wide[31:0];
					gen243_pipex_var = gen242_pipex_var[31];
					gen244_pipex_var = gen243_pipex_var.concat((ap_uint<63>)gen243_pipex_var.concat((ap_uint<62>)gen243_pipex_var.concat((ap_uint<61>)gen243_pipex_var.concat((ap_uint<60>)gen243_pipex_var.concat((ap_uint<59>)gen243_pipex_var.concat((ap_uint<58>)gen243_pipex_var.concat((ap_uint<57>)gen243_pipex_var.concat((ap_uint<56>)gen243_pipex_var.concat((ap_uint<55>)gen243_pipex_var.concat((ap_uint<54>)gen243_pipex_var.concat((ap_uint<53>)gen243_pipex_var.concat((ap_uint<52>)gen243_pipex_var.concat((ap_uint<51>)gen243_pipex_var.concat((ap_uint<50>)gen243_pipex_var.concat((ap_uint<49>)gen243_pipex_var.concat((ap_uint<48>)gen243_pipex_var.concat((ap_uint<47>)gen243_pipex_var.concat((ap_uint<46>)gen243_pipex_var.concat((ap_uint<45>)gen243_pipex_var.concat((ap_uint<44>)gen243_pipex_var.concat((ap_uint<43>)gen243_pipex_var.concat((ap_uint<42>)gen243_pipex_var.concat((ap_uint<41>)gen243_pipex_var.concat((ap_uint<40>)gen243_pipex_var.concat((ap_uint<39>)gen243_pipex_var.concat((ap_uint<38>)gen243_pipex_var.concat((ap_uint<37>)gen243_pipex_var.concat((ap_uint<36>)gen243_pipex_var.concat((ap_uint<35>)gen243_pipex_var.concat((ap_uint<34>)gen243_pipex_var.concat((ap_uint<33>)gen243_pipex_var.concat((ap_uint<32>)genpstage_EXEC_TRX_LOCAL.alu_op1_wide[31:0]))))))))))))))))))))))))))))))));
					gen245_pipex_var = (gen244_pipex_var >> genpstage_EXEC_TRX_LOCAL.alu_op2_wide[4:0]);
					genpstage_EXEC_TRX_LOCAL = gen245_pipex_var;
					break;
				case 7:
					gen246_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide ^ genpstage_EXEC_TRX_LOCAL.alu_op2_wide);
					genpstage_EXEC_TRX_LOCAL = gen246_pipex_var;
					break;
				case 8:
					gen247_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_op2_wide;
					gen248_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide & gen247_pipex_var);
					genpstage_EXEC_TRX_LOCAL = gen248_pipex_var;
					break;
			}
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_result_wide[31:0];
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_result_wide[32];
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_result_wide[31];
			gen249_pipex_var = |genpstage_EXEC_TRX_LOCAL.alu_result;
			gen250_pipex_var = ~gen249_pipex_var;
			genpstage_EXEC_TRX_LOCAL = gen250_pipex_var;
			gen251_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_op1[31];
			gen252_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_op2[31];
			gen253_pipex_var = (gen251_pipex_var & gen252_pipex_var);
			gen254_pipex_var = (gen253_pipex_var & genpstage_EXEC_TRX_LOCAL.alu_result[31]);
			gen255_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_result[31];
			gen256_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1[31] & genpstage_EXEC_TRX_LOCAL.alu_op2[31]);
			gen257_pipex_var = (gen256_pipex_var & gen255_pipex_var);
			gen258_pipex_var = (gen254_pipex_var | gen257_pipex_var);
			genpstage_EXEC_TRX_LOCAL = gen258_pipex_var;
			gen259_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_unsigned;
			gen285_cyclix_var = gen259_pipex_var;
			if (gen285_cyclix_var) {
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_CF;
			}
			gen260_pipex_var = ap_uint<1>(0);
			gen260_pipex_var = (gen260_pipex_var || gen259_pipex_var);
			gen260_pipex_var = !gen260_pipex_var;
			gen286_cyclix_var = gen260_pipex_var;
			if (gen286_cyclix_var) {
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_OF;
			}
		}
		switch (genpstage_EXEC_TRX_LOCAL) {
			case 0:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
			case 1:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_result;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
			case 2:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_CF;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
			case 3:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_OF;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
			case 4:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.nextinstr_addr;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
			case 6:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.csr_rdata;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
		}
		gen261_pipex_var = (genpstage_EXEC_TRX_LOCAL.curinstr_addr + genpstage_EXEC_TRX_LOCAL.immediate);
		genpstage_EXEC_TRX_LOCAL = gen261_pipex_var;
		switch (genpstage_EXEC_TRX_LOCAL) {
			case 0:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate;
				break;
			case 1:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_result;
				break;
		}
		gen262_pipex_var = genpstage_EXEC_TRX_LOCAL.jump_req_cond;
		gen287_cyclix_var = gen262_pipex_var;
		if (gen287_cyclix_var) {
			switch (genpstage_EXEC_TRX_LOCAL) {
				case 0:
					gen263_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_ZF;
					gen288_cyclix_var = gen263_pipex_var;
					if (gen288_cyclix_var) {
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstraddr_imm;
					}
					break;
				case 1:
					gen264_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_ZF;
					gen265_pipex_var = gen264_pipex_var;
					gen289_cyclix_var = gen265_pipex_var;
					if (gen289_cyclix_var) {
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstraddr_imm;
					}
					break;
				case 4:
					gen266_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_CF;
					gen290_cyclix_var = gen266_pipex_var;
					if (gen290_cyclix_var) {
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstraddr_imm;
					}
					break;
				case 5:
					gen267_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_CF;
					gen268_pipex_var = gen267_pipex_var;
					gen291_cyclix_var = gen268_pipex_var;
					if (gen291_cyclix_var) {
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstraddr_imm;
					}
					break;
				case 6:
					gen269_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_CF;
					gen292_cyclix_var = gen269_pipex_var;
					if (gen292_cyclix_var) {
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstraddr_imm;
					}
					break;
				case 7:
					gen270_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_CF;
					gen271_pipex_var = gen270_pipex_var;
					gen293_cyclix_var = gen271_pipex_var;
					if (gen293_cyclix_var) {
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstraddr_imm;
					}
					break;
			}
		}
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_result;
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.rs2_rdata;
		gen272_pipex_var = ~genpstage_EXEC_TRX_LOCAL.jump_req_done;
		gen273_pipex_var = gen272_pipex_var;
		gen294_cyclix_var = gen273_pipex_var;
		if (gen294_cyclix_var) {
			gen295_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen295_cyclix_var) {
				genpsticky_glbl_jump_req_cmd = genpstage_EXEC_TRX_LOCAL.jump_req;
			}
			gen296_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen296_cyclix_var) {
				genpsticky_glbl_jump_vector_cmd = genpstage_EXEC_TRX_LOCAL.jump_vector;
			}
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
			gen297_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen297_cyclix_var) {
				genpstage_EXEC_TRX_BUF = ap_uint<32>(1);
			}
		}
		gen274_pipex_var = genpstage_EXEC_TRX_LOCAL.mem_req;
		gen298_cyclix_var = gen274_pipex_var;
		if (gen298_cyclix_var) {
			gen275_pipex_var = ~genpstage_EXEC_TRX_LOCAL.data_req_done;
			gen276_pipex_var = gen275_pipex_var;
			gen299_cyclix_var = gen276_pipex_var;
			if (gen299_cyclix_var) {
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.mem_addr;
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.mem_be;
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.mem_wdata;
				gen300_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen300_cyclix_var) {
					gen301_cyclix_var = ~genmcopipe_data_mem_full_flag;
					gen302_cyclix_var = gen301_cyclix_var;
					if (gen302_cyclix_var) {
						gen317_pipex_req_struct = genpstage_EXEC_TRX_LOCAL.mem_cmd;
						gen317_pipex_req_struct = genpstage_EXEC_TRX_LOCAL.data_busreq;
						gen303_cyclix_var = genmcopipe_data_mem_req.write_nb(gen317_pipex_req_struct);
						gen304_cyclix_var = gen303_cyclix_var;
						if (gen304_cyclix_var) {
							gen277_pipex_var = ap_uint<32>(1);
							gen305_cyclix_var = !genpstage_EXEC_TRX_LOCAL.mem_cmd;
							genpstage_EXEC_TRX_BUF = gen305_cyclix_var;
							genpstage_EXEC_TRX_BUF = genmcopipe_data_mem_wr_ptr;
							genpstage_EXEC_TRX_BUF = ap_uint<1>(0);
							gen306_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.rdreq_pending;
							if (gen306_cyclix_var) {
								genmcopipe_data_mem_wr_done = ap_uint<32>(1);
							}
						}
					}
				}
				genpstage_EXEC_TRX_LOCAL = gen277_pipex_var;
				gen307_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen307_cyclix_var) {
					genpstage_EXEC_TRX_BUF = gen277_pipex_var;
				}
			}
			gen278_pipex_var = ~genpstage_EXEC_TRX_LOCAL.data_req_done;
			gen279_pipex_var = gen278_pipex_var;
			gen308_cyclix_var = gen279_pipex_var;
			if (gen308_cyclix_var) {
				gen309_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen309_cyclix_var) {
					genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
				}
				genpstage_EXEC_genctrl_active = ap_uint<32>(0);
			}
		}
		gen280_pipex_var = genpstage_EXEC_TRX_LOCAL.mem_req;
		gen310_cyclix_var = gen280_pipex_var;
		if (gen310_cyclix_var) {
			gen281_pipex_var = ~genpstage_EXEC_TRX_LOCAL.mem_cmd;
			gen282_pipex_var = gen281_pipex_var;
			gen311_cyclix_var = gen282_pipex_var;
			if (gen311_cyclix_var) {
				gen312_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.resp_done;
				if (gen312_cyclix_var) {
					genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.rdata;
				}
				gen283_pipex_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.resp_done;
				gen284_pipex_var = gen283_pipex_var;
				gen313_cyclix_var = gen284_pipex_var;
				if (gen313_cyclix_var) {
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				}
				gen285_pipex_var = ap_uint<1>(0);
				gen285_pipex_var = (gen285_pipex_var || gen284_pipex_var);
				gen285_pipex_var = !gen285_pipex_var;
				gen314_cyclix_var = gen285_pipex_var;
				if (gen314_cyclix_var) {
					gen315_cyclix_var = genpstage_EXEC_genctrl_active;
					if (gen315_cyclix_var) {
						genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
					}
					genpstage_EXEC_genctrl_active = ap_uint<32>(0);
				}
			}
		}
		gen286_pipex_var = (genpstage_EXEC_TRX_LOCAL.mem_be == ap_uint<32>(1));
		gen287_pipex_var = gen286_pipex_var;
		gen316_cyclix_var = gen287_pipex_var;
		if (gen316_cyclix_var) {
			gen288_pipex_var = genpstage_EXEC_TRX_LOCAL.load_signext;
			gen317_cyclix_var = gen288_pipex_var;
			if (gen317_cyclix_var) {
				gen289_pipex_var = genpstage_EXEC_TRX_LOCAL.mem_rdata[7:0];
				gen290_pipex_var = gen289_pipex_var[7];
				gen291_pipex_var = gen290_pipex_var.concat((ap_uint<31>)gen290_pipex_var.concat((ap_uint<30>)gen290_pipex_var.concat((ap_uint<29>)gen290_pipex_var.concat((ap_uint<28>)gen290_pipex_var.concat((ap_uint<27>)gen290_pipex_var.concat((ap_uint<26>)gen290_pipex_var.concat((ap_uint<25>)gen290_pipex_var.concat((ap_uint<24>)gen290_pipex_var.concat((ap_uint<23>)gen290_pipex_var.concat((ap_uint<22>)gen290_pipex_var.concat((ap_uint<21>)gen290_pipex_var.concat((ap_uint<20>)gen290_pipex_var.concat((ap_uint<19>)gen290_pipex_var.concat((ap_uint<18>)gen290_pipex_var.concat((ap_uint<17>)gen290_pipex_var.concat((ap_uint<16>)gen290_pipex_var.concat((ap_uint<15>)gen290_pipex_var.concat((ap_uint<14>)gen290_pipex_var.concat((ap_uint<13>)gen290_pipex_var.concat((ap_uint<12>)gen290_pipex_var.concat((ap_uint<11>)gen290_pipex_var.concat((ap_uint<10>)gen290_pipex_var.concat((ap_uint<9>)gen290_pipex_var.concat((ap_uint<8>)genpstage_EXEC_TRX_LOCAL.mem_rdata[7:0]))))))))))))))))))))))));
				genpstage_EXEC_TRX_LOCAL = gen291_pipex_var;
			}
			gen292_pipex_var = ap_uint<1>(0);
			gen292_pipex_var = (gen292_pipex_var || gen288_pipex_var);
			gen292_pipex_var = !gen292_pipex_var;
			gen318_cyclix_var = gen292_pipex_var;
			if (gen318_cyclix_var) {
				gen293_pipex_var = ap_uint<24>(0).concat((ap_uint<8>)genpstage_EXEC_TRX_LOCAL.mem_rdata[7:0]);
				genpstage_EXEC_TRX_LOCAL = gen293_pipex_var;
			}
		}
		gen294_pipex_var = (genpstage_EXEC_TRX_LOCAL.mem_be == ap_uint<32>(3));
		gen295_pipex_var = gen294_pipex_var;
		gen319_cyclix_var = gen295_pipex_var;
		if (gen319_cyclix_var) {
			gen296_pipex_var = genpstage_EXEC_TRX_LOCAL.load_signext;
			gen320_cyclix_var = gen296_pipex_var;
			if (gen320_cyclix_var) {
				gen297_pipex_var = genpstage_EXEC_TRX_LOCAL.mem_rdata[15:0];
				gen298_pipex_var = gen297_pipex_var[15];
				gen299_pipex_var = gen298_pipex_var.concat((ap_uint<31>)gen298_pipex_var.concat((ap_uint<30>)gen298_pipex_var.concat((ap_uint<29>)gen298_pipex_var.concat((ap_uint<28>)gen298_pipex_var.concat((ap_uint<27>)gen298_pipex_var.concat((ap_uint<26>)gen298_pipex_var.concat((ap_uint<25>)gen298_pipex_var.concat((ap_uint<24>)gen298_pipex_var.concat((ap_uint<23>)gen298_pipex_var.concat((ap_uint<22>)gen298_pipex_var.concat((ap_uint<21>)gen298_pipex_var.concat((ap_uint<20>)gen298_pipex_var.concat((ap_uint<19>)gen298_pipex_var.concat((ap_uint<18>)gen298_pipex_var.concat((ap_uint<17>)gen298_pipex_var.concat((ap_uint<16>)genpstage_EXEC_TRX_LOCAL.mem_rdata[15:0]))))))))))))))));
				genpstage_EXEC_TRX_LOCAL = gen299_pipex_var;
			}
			gen300_pipex_var = ap_uint<1>(0);
			gen300_pipex_var = (gen300_pipex_var || gen296_pipex_var);
			gen300_pipex_var = !gen300_pipex_var;
			gen321_cyclix_var = gen300_pipex_var;
			if (gen321_cyclix_var) {
				gen301_pipex_var = ap_uint<16>(0).concat((ap_uint<16>)genpstage_EXEC_TRX_LOCAL.mem_rdata[15:0]);
				genpstage_EXEC_TRX_LOCAL = gen301_pipex_var;
			}
		}
		gen302_pipex_var = (genpstage_EXEC_TRX_LOCAL.rd_source == ap_uint<32>(5));
		gen303_pipex_var = gen302_pipex_var;
		gen322_cyclix_var = gen303_pipex_var;
		if (gen322_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.mem_rdata;
		}
		gen304_pipex_var = genpstage_EXEC_TRX_LOCAL.ext_coproc_req;
		gen323_cyclix_var = gen304_pipex_var;
		if (gen323_cyclix_var) {
			gen324_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.resp_done;
			if (gen324_cyclix_var) {
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.rdata;
			}
			gen305_pipex_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.resp_done;
			gen306_pipex_var = gen305_pipex_var;
			gen325_cyclix_var = gen306_pipex_var;
			if (gen325_cyclix_var) {
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
			}
			gen307_pipex_var = ap_uint<1>(0);
			gen307_pipex_var = (gen307_pipex_var || gen306_pipex_var);
			gen307_pipex_var = !gen307_pipex_var;
			gen326_cyclix_var = gen307_pipex_var;
			if (gen326_cyclix_var) {
				gen327_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen327_cyclix_var) {
					genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
				}
				genpstage_EXEC_genctrl_active = ap_uint<32>(0);
			}
		}
		gen308_pipex_var = (genpstage_EXEC_TRX_LOCAL.rd_req && genpstage_EXEC_TRX_LOCAL.rd_rdy);
		gen309_pipex_var = gen308_pipex_var;
		gen328_cyclix_var = gen309_pipex_var;
		if (gen328_cyclix_var) {
			genpsticky_glbl_regfile = genpstage_EXEC_TRX_LOCAL.rd_wdata;
		}
		// Processing of next pstage busyness
		// pctrl_finish and pctrl_succ formation
		gen329_cyclix_var = genpstage_EXEC_genctrl_stalled_glbl;
		if (gen329_cyclix_var) {
			genpstage_EXEC_genctrl_finish = ap_uint<32>(0);
			genpstage_EXEC_genctrl_succ = ap_uint<32>(0);
		}
		gen330_cyclix_var = ap_uint<1>(0);
		gen330_cyclix_var = (gen330_cyclix_var || gen329_cyclix_var);
		gen330_cyclix_var = !gen330_cyclix_var;
		if (gen330_cyclix_var) {
			genpstage_EXEC_genctrl_finish = genpstage_EXEC_genctrl_occupied;
			genpstage_EXEC_genctrl_succ = genpstage_EXEC_genctrl_active;
		}
		// credit counter processing
		// asserting succ signals
		gen331_cyclix_var = genpstage_EXEC_genctrl_succ;
		if (gen331_cyclix_var) {
			gen332_cyclix_var = gen154_pipex_succreq;
			if (gen332_cyclix_var) {
				genpsticky_glbl_pc = gen155_pipex_succbuf;
			}
		}
		// processing context in case transaction is ready to propagate
		gen333_cyclix_var = genpstage_EXEC_genctrl_finish;
		if (gen333_cyclix_var) {
			// programming next stage in case transaction is able to propagate
			gen334_cyclix_var = genpstage_EXEC_genctrl_succ;
			if (gen334_cyclix_var) {
			}
			genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_EXEC_TRX_BUF = '{default:ap_uint<32>(0)};
			genpstage_EXEC_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
			genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
			genpstage_EXEC_TRX_BUF_COUNTER = (genpstage_EXEC_TRX_BUF_COUNTER - ap_uint<32>(1));
		}
		gen335_cyclix_var = ~genpstage_EXEC_TRX_BUF_COUNTER_FULL;
		genpstage_EXEC_genctrl_rdy = gen335_cyclix_var;
		genpstage_EXEC_genctrl_working = (genpstage_EXEC_genctrl_succ | genpstage_EXEC_genctrl_stalled_glbl);
		gen336_cyclix_var = genmcopipe_instr_mem_rd_done;
		if (gen336_cyclix_var) {
			genmcopipe_instr_mem_rd_ptr = genmcopipe_instr_mem_rd_ptr_next;
			genmcopipe_instr_mem_full_flag = ap_uint<32>(0);
			gen337_cyclix_var = (genmcopipe_instr_mem_rd_ptr == genmcopipe_instr_mem_wr_ptr);
			gen338_cyclix_var = gen337_cyclix_var;
			if (gen338_cyclix_var) {
				genmcopipe_instr_mem_empty_flag = ap_uint<32>(1);
			}
		}
		gen339_cyclix_var = genmcopipe_instr_mem_wr_done;
		if (gen339_cyclix_var) {
			genmcopipe_instr_mem_wr_ptr = genmcopipe_instr_mem_wr_ptr_next;
			genmcopipe_instr_mem_empty_flag = ap_uint<32>(0);
			gen340_cyclix_var = (genmcopipe_instr_mem_rd_ptr == genmcopipe_instr_mem_wr_ptr);
			gen341_cyclix_var = gen340_cyclix_var;
			if (gen341_cyclix_var) {
				genmcopipe_instr_mem_full_flag = ap_uint<32>(1);
			}
		}
		gen342_cyclix_var = genmcopipe_data_mem_rd_done;
		if (gen342_cyclix_var) {
			genmcopipe_data_mem_rd_ptr = genmcopipe_data_mem_rd_ptr_next;
			genmcopipe_data_mem_full_flag = ap_uint<32>(0);
			gen343_cyclix_var = (genmcopipe_data_mem_rd_ptr == genmcopipe_data_mem_wr_ptr);
			gen344_cyclix_var = gen343_cyclix_var;
			if (gen344_cyclix_var) {
				genmcopipe_data_mem_empty_flag = ap_uint<32>(1);
			}
		}
		gen345_cyclix_var = genmcopipe_data_mem_wr_done;
		if (gen345_cyclix_var) {
			genmcopipe_data_mem_wr_ptr = genmcopipe_data_mem_wr_ptr_next;
			genmcopipe_data_mem_empty_flag = ap_uint<32>(0);
			gen346_cyclix_var = (genmcopipe_data_mem_rd_ptr == genmcopipe_data_mem_wr_ptr);
			gen347_cyclix_var = gen346_cyclix_var;
			if (gen347_cyclix_var) {
				genmcopipe_data_mem_full_flag = ap_uint<32>(1);
			}
		}
		gen348_cyclix_var = genmcopipe_coproc_M_if_rd_done;
		if (gen348_cyclix_var) {
			genmcopipe_coproc_M_if_rd_ptr = genmcopipe_coproc_M_if_rd_ptr_next;
			genmcopipe_coproc_M_if_full_flag = ap_uint<32>(0);
			gen349_cyclix_var = (genmcopipe_coproc_M_if_rd_ptr == genmcopipe_coproc_M_if_wr_ptr);
			gen350_cyclix_var = gen349_cyclix_var;
			if (gen350_cyclix_var) {
				genmcopipe_coproc_M_if_empty_flag = ap_uint<32>(1);
			}
		}
		gen351_cyclix_var = genmcopipe_coproc_M_if_wr_done;
		if (gen351_cyclix_var) {
			genmcopipe_coproc_M_if_wr_ptr = genmcopipe_coproc_M_if_wr_ptr_next;
			genmcopipe_coproc_M_if_empty_flag = ap_uint<32>(0);
			gen352_cyclix_var = (genmcopipe_coproc_M_if_rd_ptr == genmcopipe_coproc_M_if_wr_ptr);
			gen353_cyclix_var = gen352_cyclix_var;
			if (gen353_cyclix_var) {
				genmcopipe_coproc_M_if_full_flag = ap_uint<32>(1);
			}
		}
		gen354_cyclix_var = genmcopipe_coproc_custom0_if_rd_done;
		if (gen354_cyclix_var) {
			genmcopipe_coproc_custom0_if_rd_ptr = genmcopipe_coproc_custom0_if_rd_ptr_next;
			genmcopipe_coproc_custom0_if_full_flag = ap_uint<32>(0);
			gen355_cyclix_var = (genmcopipe_coproc_custom0_if_rd_ptr == genmcopipe_coproc_custom0_if_wr_ptr);
			gen356_cyclix_var = gen355_cyclix_var;
			if (gen356_cyclix_var) {
				genmcopipe_coproc_custom0_if_empty_flag = ap_uint<32>(1);
			}
		}
		gen357_cyclix_var = genmcopipe_coproc_custom0_if_wr_done;
		if (gen357_cyclix_var) {
			genmcopipe_coproc_custom0_if_wr_ptr = genmcopipe_coproc_custom0_if_wr_ptr_next;
			genmcopipe_coproc_custom0_if_empty_flag = ap_uint<32>(0);
			gen358_cyclix_var = (genmcopipe_coproc_custom0_if_rd_ptr == genmcopipe_coproc_custom0_if_wr_ptr);
			gen359_cyclix_var = gen358_cyclix_var;
			if (gen359_cyclix_var) {
				genmcopipe_coproc_custom0_if_full_flag = ap_uint<32>(1);
			}
		}
	}
}
